### ISSUE TITLE
lock version of plotly.js used in react_multi to specific version rather than plotly-latest

### ISSUE THREAD

**Issue by michaelbabyn** [nicolaskruchten/fig2pen#1]
it might also be useful to lock it to the version of plotly used in `dash_core_components._js_dist` since reproducing issues from a Dash app is probably a pretty common use case for `react_multi()`

**Comment by nicolaskruchten** [comment]
`fig2pen` has no way of knowing the version AFAIK. The best we could do is provide a kwarg for the version.

**Comment by michaelbabyn** [comment]
yeah, then we can document passing in `dcc._js_dist[0]['external_url']` to that kwarg if they're a Dash user

**Comment by nicolaskruchten** [comment]
ah yeah. PRs welcome! this is a pretty tiny piece of code.

**Comment by nicolaskruchten** [comment]
This is now doable with the `cdn_version` argument, which now defaults to `plotly.offline.get_plotlyjs_version()` but you can pass in `dcc._js_dist[0]['external_url']` manually if you like.
